name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build:
    name: build-release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - build: linux
          os: ubuntu-latest
          rust: nightly
          target: x86_64-unknown-linux-musl
          strip: x86_64-linux-musl-strip
        - build: macos
          os: macos-latest
          rust: nightly
          target: x86_64-apple-darwin
        - build: win-msvc
          os: windows-latest
          rust: nightly
          target: x86_64-pc-windows-msvc
        - build: win-gnu
          os: windows-latest
          rust: nightly-x86_64-gnu
          target: x86_64-pc-windows-gnu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}

    - name: Build release binary
      run: cargo build --release

    - name: Package artifact (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        set -euxo pipefail
        BIN_NAME="datatui"
        TAG_NAME="${GITHUB_REF_NAME}"
        OS="${RUNNER_OS}"
        ARCH="${RUNNER_ARCH}"
        ARTIFACT="datatui-${TAG_NAME}-${OS}-${ARCH}.tar.gz"
        mkdir -p dist
        cp "target/release/${BIN_NAME}" dist/
        [ -f README.md ] && cp README.md dist/ || true
        [ -f LICENSE ] && cp LICENSE dist/ || true
        tar -C dist -czf "${ARTIFACT}" .
        echo "ARTIFACT=${ARTIFACT}" >> $GITHUB_ENV

    - name: Package artifact (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $ErrorActionPreference = "Stop"
        $BinName = "datatui.exe"
        $TagName = "${env:GITHUB_REF_NAME}"
        $Target = "${{ matrix.target }}"
        $Artifact = "datatui-$TagName-$Target.zip"
        New-Item -ItemType Directory -Force -Path dist | Out-Null
        Copy-Item "target\release\datatui.exe" "dist\"
        if (Test-Path "README.md") { Copy-Item "README.md" "dist\" }
        if (Test-Path "LICENSE") { Copy-Item "LICENSE" "dist\" }
        Compress-Archive -Path "dist\*" -DestinationPath $Artifact
        Add-Content -Path $env:GITHUB_ENV -Value "ARTIFACT=$Artifact"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT }}
        path: ${{ env.ARTIFACT }}
        if-no-files-found: error

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist
        merge-multiple: true

    - name: Publish Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*
        draft: false
        prerelease: ${{ contains(github.ref_name, '-rc') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-alpha') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish to crates.io
    needs: release
    uses: ./.github/workflows/publish.yml
    with:
      version: ${{ github.ref_name }}
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}


